version: "3"
services:
  mongodb:
    build: mongo/
    ports:
      - "27017:27017"
    networks:
      - default
  reddit_parser:
    build: reddit_parser/
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - default
  web_api:
    build: web_api/
    depends_on:
      - mongodb
      - reddit_parser
    ports:
      - "8080:8080"
    links:
      - mongodb
    networks:
      - default
networks:
  default:
    driver: bridge
